#!/bin/bash
# Author: Ricardo Gomes
#
# Purpose: switch to a light theme on everything possible (st, i3, polybar, gtk, ...)
#



echo "Lumos"

rm $HOME/.Xresources

ln -sf $HOME/.config/themes/Xresources.mostly-bright $HOME/.Xresources

xrdb load $HOME/.Xresources

cd /data/development/local_builds/st

make 
sudo make install

cd -
